version: '3'

volumes:
  production_elasticsearch_data: {}

services:
  server: &server
    build:
      context: .
      dockerfile: ./compose/production/server/Dockerfile
    image: ecli_indexer_production_server
    depends_on:
      - elasticsearch
    env_file:
      - ./.envs/.production/.server
    ports:
      - "9100:9100"
    command: /start
    restart: always

  elasticsearch:
    build:
      context: .
      dockerfile: ./compose/production/elasticsearch/Dockerfile
    image: ecli_indexer_production_elasticsearch
    env_file:
      - ./.envs/.production/.elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - production_elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"
    restart: always
  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.0
    depends_on:
      - elasticsearch
    ports:
      - "127.0.0.1:5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    restart: always
