version: '3'

volumes:
  production_elasticsearch_data: {}

services:
  server: &server
    build:
      context: .
      dockerfile: ./compose/local/server/Dockerfile
    image: ecli_indexer_local_server
    depends_on:
      - elasticsearch
    env_file:
      - ./.envs/.local/.server
    ports:
      - "9100:9100"
    command: /start
    restart: always

  elasticsearch:
    build:
      context: .
      dockerfile: ./compose/production/elasticsearch/Dockerfile
    image: ecli_indexer_production_elasticsearch
    env_file:
      - ./.envs/.local/.elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - production_elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
